---
title: "Reproducible Research: Peer Assessment 1"
output: html_document:
keep_md: true
---

## Loading and preprocessing the data
library(ggplot2)
unzip("activity.zip")
data <- read.csv("activity.csv", colClasses = c("integer", "Date", "factor"))
data$month <- as.numeric(format(data$date, "%m"))
notNA <- na.omit(data)
rownames(notNA) <- 1:nrow(notNA)
head(notNA)
dim(notNA)

## Histogram for total nos of step per day 
ggplot(notNA, aes(date, steps)) + geom_bar(stat = "identity", colour = "green", fill = "green", width = 0.7) + facet_grid(. ~ month, scales = "free") + labs(title = "Histogram of Total Number of Steps Taken Each Day", x = "Date", y = "Total number of steps")


## What is the average daily activity pattern?
totalSteps <- aggregate(notNA$steps, list(Date = notNA$date), FUN = "sum")$x
mean(totalSteps)
median(totalSteps)

## What is the average daily activity pattern
avgSteps <- aggregate(notNA$steps, list(interval = as.numeric(as.character(notNA$interval))), FUN = "mean")
names(avgSteps)[2] <- "meanOfSteps"
ggplot(avgSteps, aes(interval, meanOfSteps)) + geom_line(color = "steelblue", size = 0.8) + labs(title = "Time Series Plot of the 5-minute Interval", x = "5-minute intervals", y = "Average Number of Steps Taken")


## Accounting for missing values

# Strategy is to use the mean for that 5-minute interval to fill each NA value in the steps column. Create a new dataset that is equal to the original dataset but with the missing data filled in.

sum(is.na(data))
newData <- data 
for (i in 1:nrow(newData)) {
    if (is.na(newData$steps[i])) {
        newData$steps[i] <- avgSteps[which(newData$interval[i] == avgSteps$interval), ]$meanOfSteps
    }
}

head(newData)
sum(is.na(newData))
ggplot(newData, aes(date, steps)) + geom_bar(stat = "identity", colour = "green", fill = "green",width = 0.7) + facet_grid(. ~ month, scales = "free") + labs(title = "Histogram of Total Number of Steps Taken Each Day (no missing data)", x = "Date", y = "Total number of steps")

##Mean total number of steps taken per day:
newTotalSteps <- aggregate(newData$steps, list(Date = newData$date), FUN = "sum")$x
newMean <- mean(newTotalSteps)
newMean

#Median total number of steps taken per day:

newMedian <- median(newTotalSteps)
newMedian

#Compare them with the two before imputing missing data:

oldMean <- mean(totalSteps)
oldMedian <- median(totalSteps)
newMean - oldMean
newMedian - oldMedian


## Are there differences in activity patterns between weekdays and weekends?
head(newData)
newData$weekdays <- factor(format(newData$date, "%A"))
levels(newData$weekdays)
levels(newData$weekdays) <- list(weekday = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), weekend = c("Saturday", "Sunday"))
levels(newData$weekdays)
table(newData$weekdays)

avgSteps <- aggregate(newData$steps, list(interval = as.numeric(as.character(newData$interval)),weekdays = newData$weekdays),
FUN = "mean")
names(avgSteps)[3] <- "meanOfSteps"
library(lattice)
xyplot(avgSteps$meanOfSteps ~ avgSteps$interval | avgSteps$weekdays, layout = c(1, 2), type = "l", xlab = "Interval", ylab = "Number of steps")
